base_link2traffic_light_camera:
  x: 2.07
  y: 0.0
  z: 1.57
  roll: 0.0
  pitch: -0.3
  yaw: 0.0
base_link2camera1:
  x: 1.0
  y: 0.55
  z: 1.63
  roll: -0.025
  pitch: 0.315
  yaw: 1.035
base_link2camera2:
  x: 0.8
  y: -0.55
  z: 1.63
  roll: -0.025
  pitch: 0.29
  yaw: -2.12
base_link2camera3:
  x: 1.0
  y: -0.55
  z: 1.63
  roll: -0.01
  pitch: 0.29
  yaw: -1.04
base_link2camera4:
  x: 0.8
  y: 0.55
  z: 1.63
  roll: 0.0
  pitch: 0.315
  yaw: 2.0943951
base_link2camera5:
  x: 0.93
  y: 0.0
  z: 1.96
  roll: 0.0
  pitch: -0.015
  yaw: -0.005
base_link2camera6:
  x: 0.87
  y: 0.0
  z: 1.96
  roll: 0.0
  pitch: -0.01
  yaw: 3.125
base_link2velodyne_top:
  x: 0.9
  y: 0.0
  z: 2.0
  roll: 0.0
  pitch: 0.0
  yaw: -0.0197
base_link2velodyne_left:
  x: 0.9
  y: 0.6
  z: 2.0
  roll: 0.0
  pitch: 0.69813170079
  yaw: 1.56579632679
base_link2velodyne_right:
  x: 0.9
  y: -0.6
  z: 2.0
  roll: 0.0
  pitch: 0.69813170079
  yaw: -1.59079632679
base_link2imu_gx5:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 3.14159265359
  pitch: 0.0
  yaw: 0.0
base_link2imu_tamagawa:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 3.14159265359
  pitch: 0.0
  yaw: 0.0
base_link2gnss:
  x: 0.0
  y: 0.0
  z: 1.8
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
