wheel_radius: 0.39
wheel_width: 0.42
wheel_base: 2.79 # between front wheel center and rear wheel center
wheel_tread: 1.63 # between left wheel center and right wheel center
front_overhang: 1.29 # between front wheel center and vehicle front
rear_overhang: 1.1 # between rear wheel center and vehicle rear 
vehicle_height: 2.0
