wheel_radius: 0.341
wheel_width: 0.42
wheel_base: 2.63 # between front wheel center and rear wheel center
wheel_tread: 1.55 # between left wheel center and right wheel center
front_overhang: 1.29 # between front wheel center and vehicle front
rear_overhang: 1.1 # between rear wheel center and vehicle rear 
vehicle_length: 5.02 # rear_overhang + front_overhang + wheel_base
vehicle_width: 1.97 # wheel_tread + wheel_width
vehicle_height: 2.0
