base_link2camera:
  x: 0.9917571
  y: 0.0
  z: 2.0365
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
base_link2velodyne:
  x: 0.9401971
  y: 0.0
  z: 2.1263
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
base_link2imu:
  x: 1.2
  y: 0.0
  z: 1.8
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
