required_modules:
  manual_driving: []

  autonomous_driving:
    - "/control/autonomous_driving"
    - "/control/command_gate"
    - "/localization"
    - "/map"
    - "/perception"
    - "/planning"
    - "/sensing"
    - "/system"
    - "/vehicle"

  remote_control:
    - "/control/command_gate"
    - "/control/remote_control"
    - "/system"
    - "/vehicle"

  safe_stop:
    - "/control/command_gate"
    - "/map"
    - "/system"
    - "/vehicle"

  emergency_stop:
    - "/control/command_gate"
    - "/system"
    - "/vehicle"
