update_rate: 10
required_conditions:
  manual_driving:
    - vehicle

  autonomous_driving:
    - control
    - localization
    - map
    - monitoring
    - perception
    - planning
    - safety
    - sensing
    - vehicle

  remote_control:
    - control
    - internet_connection
    - vehicle

  safe_stop:
    - map
    - redundant_system
    - vehicle

  emergency_stop:
    - vehicle
