analyzers:
  perception:
    type: diagnostic_aggregator/AnalyzerGroup
    path: perception
    analyzers:
      topic_timeout:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_timeout
        contains: ": perception_topic_timeout"
        num_items: 0

      topic_rate:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_rate
        contains: ": perception_topic_rate"
        num_items: 0
