analyzers:
  planning:
    type: diagnostic_aggregator/AnalyzerGroup
    path: planning
    analyzers:
      topic_timeout:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_timeout
        contains: ": planning_topic_timeout"
        num_items: 0

      topic_rate:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_rate
        contains: ": planning_topic_rate"
        num_items: 0
