analyzers:
  redundant_system:
    type: diagnostic_aggregator/AnalyzerGroup
    path: redundant_system
    analyzers:
      dummy:
        type: diagnostic_aggregator/GenericAnalyzer
        path: dummy
        contains: "__dummy__"
        num_items: 1
