analyzers:
  remote_control:
    type: diagnostic_aggregator/AnalyzerGroup
    path: remote_control
    analyzers:
      topic_status:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_status
        contains: ": remote_control_topic_status"
        num_items: 0

      internet_connection:
        type: diagnostic_aggregator/GenericAnalyzer
        path: internet_connection
        contains: ": internet_connection"
        num_items: 0

      remote_cmd_converter:
        type: diagnostic_aggregator/GenericAnalyzer
        path: remote_cmd_converter
        contains: ": remote_cmd_converter"
        num_items: 0
