analyzers:
  vehicle:
    type: diagnostic_aggregator/AnalyzerGroup
    path: vehicle
    analyzers:
      topic_timeout:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_timeout
        contains: ": vehicle_topic_timeout"
        num_items: 0

      topic_rate:
        type: diagnostic_aggregator/GenericAnalyzer
        path: topic_rate
        contains: ": vehicle_topic_rate"
        num_items: 0
